-- A constructor function or class could be helpful for organizing these. 
--     You might also want to include a seeds.sql file to pre-populate your database, 
--         making the development of individual features much easier.